all: uvcompress

uvcompress: uvcompress.c
        cc -O3 -Wall -std=c18 uvcompress.c -o uvcompress -lm

clean:
        rm -f uvcompress                                                                                                                                    ~                                                                                                                                     ~                                                                                                                                     ~                             